In [4]:
import cv2
import numpy as np

image_path = "data/image.jpg"
img_bgr = cv2.imread(image_path, cv2.IMREAD_COLOR)

if img_bgr is None:
    raise FileNotFoundError(f"Could not read image at: {image_path}")a

print("Image shape (H, W, C):", img_bgr.shape)
print(type(img_bgr))
print("Data type:", img_bgr.dtype)

# Lấy tên kiểu dữ liệu trực tiếp dưới dạng chuỗi văn bản để tránh lỗi hàm nội bộ


print("data: ", img_bgr)

print(type(img_bgr))

cv2.imshow("Original image", img_bgr)
cv2.waitKey(0)          # press any key to close the window
cv2.destroyAllWindows()

Image shape (H, W, C): (720, 1280, 3)
<class 'numpy.ndarray'>
Data type: uint8
data:  [[[ 17  21  22]
  [ 18  22  23]
  [ 20  24  25]
  ...
  [204 202 201]
  [204 202 201]
  [204 202 201]]

 [[ 16  20  21]
  [ 17  21  22]
  [ 19  23  24]
  ...
  [204 202 201]
  [204 202 201]
  [204 202 201]]

 [[ 15  19  20]
  [ 15  19  20]
  [ 16  20  21]
  ...
  [204 202 201]
  [203 201 200]
  [203 201 200]]

 ...

 [[156 163 158]
  [154 161 156]
  [154 160 155]
  ...
  [138 143 142]
  [138 143 142]
  [138 143 142]]

 [[155 162 157]
  [154 161 156]
  [155 161 156]
  ...
  [138 143 142]
  [138 143 142]
  [138 143 142]]

 [[155 162 157]
  [154 161 156]
  [155 161 156]
  ...
  [138 143 142]
  [138 143 142]
  [138 143 142]]]
<class 'numpy.ndarray'>


In [5]:
# Convert to grayscale
img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

# Convert to binary image (thresholding)
thresh_value, img_binary = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY)

print("Threshold used:", thresh_value)
print("Gray image shape:", img_gray.shape)
print("Binary image shape:", img_binary.shape)

cv2.imshow("Grayscale image", img_gray)
cv2.moveWindow("Grayscale image", 0, 0)

cv2.imshow("Binary image", img_binary)
cv2.moveWindow("Binary image", img_gray.shape[1] + 20, 0)

cv2.waitKey(0)          # press any key to close the windows
cv2.destroyAllWindows()

Threshold used: 127.0
Gray image shape: (720, 1280)
Binary image shape: (720, 1280)


In [ ]:
import cv2

cap = cv2.VideoCapture(2)  

while True:
    ret, frame = cap.read()
    if not ret:
        print("Failed to read frame from camera")
        break

    cv2.imshow("Camera", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


In [ ]:
cap = cv2.VideoCapture(1)  

while True:
    ret, frame = cap.read()
    if not ret:
        print("Failed to read frame from camera")
        break

    h, w, c = frame.shape
    cx, cy = w // 2, h // 2
    b, g, r = frame[cy, cx]

    text_size = f"Size: {w}x{h}"
    text_rgb = f"RGB at ({cx},{cy}): ({r},{g},{b})"

    cv2.putText(frame, text_size, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.putText(frame, text_rgb, (10, 70), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.circle(frame, (cx, cy), 5, (0, 0, 255), -1)

    cv2.imshow("Camera", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()